### ISSUE TITLE
Error in observer.next ...

### ISSUE THREAD

**Issue by vlavorini** [VulcanJS/vulcan-docs#14]
Hello,
 I'm trying to run the tutorial, "Understanding the Vulcan Framework" but I got stuck after adding the fragments.
The page loads, the list of movies appears  but in less than a second the page reloads and I got this error.

Here the stack from the browser console:

`Error in observer.next 
 render@http://localhost:3000/packages/my-package.js?hash=46800dd09de94b43efcca733ca33a2f697d0a576:251:13
require<.node_modules["react-dom"].lib["ReactCompositeComponent.js"]</ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext/renderedElement<@http://localhost:3000/packages/modules.js?hash=9508cf4817c26a053bc71793130dac2e819df54d:103947:16
measureLifeCyclePerf@http://localhost:3000/packages/modules.js?hash=9508cf4817c26a053bc71793130dac2e819df54d:103226:12
require<.node_modules["react-dom"].lib["ReactCompositeComponent.js"]</ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext@http://localhost:3000/packages/modules.js?hash=9508cf4817c26a053bc71793130dac2e819df54d:103946:25
require<.node_modules["react-dom"].lib["ReactCompositeComponent.js"]</ReactCompositeComponent._renderValidatedComponent@http://localhost:3000/packages/modules.js?hash=9508cf4817c26a053bc71793130dac2e819df54d:103973:27
require<.node_modules["react-dom"].lib["ReactCompositeComponent[…]  modules.js:21243:37`

No errors from the server.

I'm on a Mac Sierra, Meteor 1.4.3.2, npm 4.1.2, node 7.6.0. Any hints?

Thank you guys!

**Comment by SachaG** [comment]
Any error on the server?

**Comment by vlavorini** [comment]
no, no errors from the server. Just a warning about BCrypt:
`Note: you are using a pure-JavaScript implementation of bcrypt.`

which I think is not related

**Comment by SachaG** [comment]
What's `http://localhost:3000/packages/my-package.js` by the way? Why would you have a file there?

**Comment by vlavorini** [comment]
I don't now, it's automatically created by Meteor. It contains all the code I have write in the files as the tutorial describe, and it's in:

`./.meteor/local/build/programs/server/packages/my-package.js`
and
`./.meteor/local/build/programs/web.browser/packages/my-package.js`

**Comment by SachaG** [comment]
Oh ok if it's in there that's fine then, sorry. Let's try something else then, can you paste in your `.meteor/versions` file? You might have some outdated packages?

**Comment by vlavorini** [comment]
here: 

accounts-base@1.2.15
accounts-password@1.3.4
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.5
autoupdate@1.3.12
babel-compiler@6.14.1
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.1
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.1.9
callback-hook@1.0.10
check@1.2.5
coffeescript@1.12.3_1
ddp@1.2.5
ddp-client@1.3.3
ddp-common@1.2.8
ddp-rate-limiter@1.0.7
ddp-server@1.3.13
deps@1.0.12
diff-sequence@1.0.7
ecmascript@0.6.3
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
fortawesome:fontawesome@4.5.0
fourseven:scss@3.13.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jparker:crypto-core@0.1.0
jparker:crypto-md5@0.1.1
jparker:gravatar@0.5.1
jquery@1.11.10
livedata@1.0.18
localstorage@1.0.12
logging@1.1.17
mdg:validation-error@0.5.1
meteor@1.6.1
meteor-base@1.0.4
meteorhacks:inject-initial@1.0.4
meteorhacks:picker@1.0.3
minifier-css@1.2.16
minifier-js@1.2.18
minimongo@1.0.21
modules@0.7.9
modules-runtime@0.7.9
mongo@1.1.16
mongo-id@1.0.6
my-package@0.0.0
nova:base-components@1.2.0
nova:base-styles@1.2.0
nova:categories@1.2.0
nova:comments@1.2.0
nova:core@1.2.0
nova:forms@1.2.0
nova:i18n-en-us@1.2.0
nova:lib@1.2.0
nova:posts@1.2.0
nova:routing@1.2.0
nova:users@1.2.0
nova:voting@1.2.0
npm-bcrypt@0.9.2
npm-mongo@2.2.24
observe-sequence@1.0.16
ordered-dict@1.0.9
percolatestudio:synced-cron@1.1.0
promise@0.8.8
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.7
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.3
softwarerero:accounts-t9n@1.3.9
spacebars@1.0.14
spacebars-compiler@1.1.1
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@1.2.3
standard-minifiers@1.0.6
std:accounts-ui@1.2.19
tmeasday:check-npm-versions@0.3.1
tracker@1.1.2
ui@1.0.12
underscore@1.0.10
url@1.1.0
webapp@1.3.14
webapp-hashing@1.0.9

Merci pour ton aide :)

**Comment by SachaG** [comment]
No that looks alright to me… What if you try the `framework-demo` package directly instead of following the tutorial, does that work any better?

**Comment by vlavorini** [comment]
In order to enable the `framework-demo` I have to re-add in the `.meteor/packages` the packages the tutorial ask to delete. And if I do so, I get an error: `Error: There is already a collection named "movies"`.

So I have to change the name of the collection in `packages/my-package/lib/modules/collection.js`, and if I do so the demo works good.

So the problem is in the tutorial package... But I don't have idea where to find it

**Comment by SachaG** [comment]
Maybe you can just go file by file and compare your package's code with `framework-demo`'s code?

**Comment by vlavorini** [comment]
ok, i try. Thank you!

**Comment by vlavorini** [comment]
That's weird: after checking everything, I just copied  `framework-demo` in `my-package`, and modified the name in `my-package/package.js`. But pointing to `localhost:3000/movies` I have the same error!

So the problem should not be in the files, but somewhere else in the framework.

Moreover, even if the `framework-demo` is commented, as I point to `localhost:3000/` I see it appearing.

Is there a ghost within my framework?

**Comment by SachaG** [comment]
maybe try `meteor reset`?

**Comment by vlavorini** [comment]
Tried, but nothing changes. Still the same error in 'localhost:3000/movies', and still the presence of `framework-demo` in `localhost:3000`...

I did not mentioned that I always have two warnings on the browser console:
`"Warning: fragment with name UsersCurrent already exists.`
and
`Warning: React attempted to reuse markup in a container but the checksum was invalid ....'

But that should not be part of the problem, since they are present in both the addresses
