### ISSUE TITLE
should modules include a subdirectory in example-movies?

### ISSUE THREAD

**Issue by WitaliB** [VulcanJS/vulcan-docs#24]
I am going through the example-movies and there is an inconsistency in using the subdirectory movies.

Is your intention to use movies directory? (I think so):
my-package/modules/movies

Or put all the files directly into the modules folder?
As used here:

> We’re now ready to set up our Movies collection. Create a new collection.js file inside modules:

**Comment by SachaG** [comment]
Thanks for the PR!
