### ISSUE TITLE
autoValue in schema did not work for me

### ISSUE THREAD

**Issue by witalib** [VulcanJS/vulcan-docs#25]
I used the autoValue as in the docs for the example-movies:
```
createdAt: {
  type: Date,
  viewableBy: ['guests'],
  optional: true,
  autoValue: (documentOrModifier) => {
    if (documentOrModifier && !documentOrModifier.$set) return new Date() // if this is an insert, set createdAt to current timestamp  
  }
},
```

but I got `createdAt: null`

so I used the code from the included package:
```
onInsert: (document, currentUser) => {
  return new Date();
}
```
which works fine for me. (Why did you pass the args?)

I reset the project with meteor reset but got null again. Not sure if it was a problem with my configuration or a problem with the code.

**Comment by SachaG** [comment]
Yes, sorry about that, the docs need to be updated. The second syntax is correct :)

**Comment by witalib** [comment]
no problem. I can create a pull request with the needed updates for the movies example if you want. 
I never did pull requests before. Should I put all changes in one pull request or make several of them?

**Comment by SachaG** [comment]
That'd be great! And you can put all changes in one PR as long as they're all related :)

**Comment by WitaliB** [comment]
They are all related to the movies example. Changes by themself are different in nature ;)

**Comment by SachaG** [comment]
Yeah a single PR is fine.
