### ISSUE TITLE
Movie Example resolveAs Error

### ISSUE THREAD

**Issue by artisin** [VulcanJS/vulcan-docs#33]
I'm pulling this issue in case anyone else runs into the same Error. The docs for the [Field-Resolvers](http://docs.vulcanjs.org/data-loading.html#Field-Resolvers) utilize the new  `resolveAs` Object schema syntax which has not been merged into the master yet. This means you either have to use the old syntax `resolveAs: 'user: User'` or you have to use the `devel` branch.

**Comment by eric-burel** [comment]
Closed as stale, this is now in the master branch.
