### ISSUE TITLE
Add search to the docs

### ISSUE THREAD

**Issue by Haroenv** [VulcanJS/vulcan-docs#45]
Algolia offers [docsearch](https://community.algolia.com/docsearch/), which is free. Would be nice to have here

**Comment by SachaG** [comment]
Agreed! PR welcome ;)

**Comment by Haroenv** [comment]
Hi there,

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page


<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />

<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'ab091fbd89cda3abd54a35c4441b3e9b',
  indexName: 'vulcanjs',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>

- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/vulcanjs.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by SachaG** [comment]
That's awesome, thanks so much!

**Comment by SachaG** [comment]
Done :) http://docs.vulcanjs.org/

**Comment by Haroenv** [comment]
Love it!
