### ISSUE TITLE
Add a "community packages" page

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/vulcan-docs#63]
What do you guys think about adding a page that would list some useful packages developped for vulcan? I'm thinking about stuff like [ErikDakoda/vulcan-material-ui](https://github.com/ErikDakoda/vulcan-material-ui) that could be useful to some people, but that don't necessarely fit in the main Vulcan repo. 
I'm currently developing an app using Vulcan and i will write and maintain public vulcan packages making some integrations easy (for example an Algolia integration package). 
Once people share their package to the public, they should be able to add it to the list on the docs to make it easier for people to find it, right? 
This is just my point of view, this thread is open for further discussion

**Comment by SachaG** [comment]
There is a page here: http://docs.vulcanjs.org/plugins.html

We can use that for now?

**Comment by Apollinaire** [comment]
That would work yes! Do you have some other repos we might add to it? I'll write the page and make a PR for it if it's fine for you

**Comment by SachaG** [comment]
There is https://github.com/voodooattack/file-scalar

Otherwise maybe you can ask people in the Slack chatroom? While you're at it, it would also be great to compile a list of active Vulcan apps, people always ask for examples and I never know what to say :)

**Comment by ErikDakoda** [comment]
@Apollinaire I'd be happy if you would add my package https://github.com/ErikDakoda/vulcan-material-ui to the plugins page. I am also thinking about releasing some of my other general-purpose packages to the Vulcan community. For example I have a Contentful integration.
